### PR TITLE
Clean up warnings

### LINKED ISSUE #2: share appropriate code between native and wasm
There are two implementations of the EE.  One in src/main.rs and one in ee/src/main.rs.  This should be consolidated.

### PR DESCRIPTION
**Pull request by lightclient**
Just trying to clear some warnings in the repo and resolve #2.

### CODE REVIEW

**Review by jrhea — COMMENTED** [review]
Does the README.md need to be updated with new build/run instructions?  Does `cargo run` still run native and `cargo test` only run wasm?

**Review by jrhea — COMMENTED** [review]
Do you use `cargo fmt`?  If not, what do you use (so i can match your style)?

**Review by jrhea — APPROVED** [review]
Except for the comment regarding readme updates.  lgtm

**Comment by lightclient** [comment]
> Do you use `cargo fmt`? If not, what do you use (so i can match your style)?

I do use `cargo fmt`, I have my editor run it on the current file every time I save it.

**Pull request merged**
